PRODUCT_COPY_FILES += \
    device/rockchip/rk3188/gpu/libpvr/pvrsrvctl:/system/vendor/bin/pvrsrvctl\
    device/rockchip/rk3188/gpu/libpvr/gralloc.rk30xxb.so:system/vendor/lib/hw/gralloc.rk30xxb.so\
    device/rockchip/rk3188/gpu/libpvr/libEGL_POWERVR_SGX540_130.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_130.so\
    device/rockchip/rk3188/gpu/libpvr/libGLESv1_CM_POWERVR_SGX540_130.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_130.so\
    device/rockchip/rk3188/gpu/libpvr/libGLESv2_POWERVR_SGX540_130.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_130.so\
    device/rockchip/rk3188/gpu/libpvr/libIMGegl.so:system/vendor/lib/libIMGegl.so\
    device/rockchip/rk3188/gpu/libpvr/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so\
    device/rockchip/rk3188/gpu/libpvr/libglslcompiler.so:system/vendor/lib/libglslcompiler.so\
    device/rockchip/rk3188/gpu/libpvr/libpvr2d.so:system/vendor/lib/libpvr2d.so\
    device/rockchip/rk3188/gpu/libpvr/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so\
    device/rockchip/rk3188/gpu/libpvr/libsrv_init.so:system/vendor/lib/libsrv_init.so\
    device/rockchip/rk3188/gpu/libpvr/libsrv_um.so:system/vendor/lib/libsrv_um.so\
    device/rockchip/rk3188/gpu/libpvr/libusc.so:system/vendor/lib/libusc.so\
    device/rockchip/rk3188/gpu/libpvr/rklfb.ko:system/lib/modules/rklfb.ko\
    device/rockchip/rk3188/gpu/libpvr/pvrsrvkm.ko:system/lib/modules/pvrsrvkm.ko\
    device/rockchip/rk3188/gpu/libpvr/libperformance_runtime.so:system/lib/libperformance_runtime.so\
    device/rockchip/rk3188/gpu/libpvr/gpu.$(TARGET_BOARD_HARDWARE).so:system/lib/hw/gpu.$(TARGET_BOARD_HARDWARE).so\
    device/rockchip/rk3188/gpu/libpvr/performance_info.xml:system/etc/performance_info.xml
